# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g @angular/cli
  - npm install
  - npm start
  artifacts:
    paths:
    - public
  only:
    - master